### ISSUE TITLE
Unhandled exception: String cannot be of zero length.

### ISSUE THREAD

**Issue by suryadesign** [RickStrahl/QfxToQboConverter#1]
Hi Rick--

Thanks for creating this program.  Unfortunately, I attempted to run this on a QIF file but received the following error:
`C:\Users\xxxx\Downloads>QfxToQboConverter.exe 2021-09-05_transaction_download.qif

Unhandled Exception: System.ArgumentException: String cannot be of zero length.
Parameter name: oldValue
   at System.String.ReplaceInternal(String oldValue, String newValue)
   at System.String.Replace(String oldValue, String newValue)
   at QfxToQboConverter.Program.Main(String[] args)`

I'm happy to send you the qif file directly for debug purposes.

Thanks!
Sandheep

**Comment by lpmlpm** [comment]
Same issue here...

`C:\Users\lpm\Desktop>QfxToQboConverter.exe 0133500050014518.QIF -n

Unhandled Exception: System.ArgumentException: String cannot be of zero length.
Parameter name: oldValue
   at System.String.ReplaceInternal(String oldValue, String newValue)
   at System.String.Replace(String oldValue, String newValue)
   at QfxToQboConverter.Program.Main(String[] args)
`
